[project]
name = "ngspice-cosim-inv"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ipympl>=0.9.7",
    "matplotlib>=3.10.3",
    "notebook>=7.4.3",
    "numpy>=2.2.6",
    "scipy>=1.15.3",
]
